### ISSUE TITLE
Missing dependency on rpm

### ISSUE THREAD

**Issue by EvaSDK** [rpm-software-management/rpmlint#210]
```
$ pip install git+https://github.com/rpm-software-management/rpmlint
Collecting git+https://github.com/rpm-software-management/rpmlint
  Cloning https://github.com/rpm-software-management/rpmlint to /tmp/pip-req-build-dnho4wz2
  Running command git clone -q https://github.com/rpm-software-management/rpmlint /tmp/pip-req-build-dnho4wz2
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-dnho4wz2/setup.py", line 9, in <module>
        from rpmlint import __version__
      File "/tmp/pip-req-build-dnho4wz2/rpmlint/__init__.py", line 5, in <module>
        from rpmlint.rpmdiff import Rpmdiff
      File "/tmp/pip-req-build-dnho4wz2/rpmlint/rpmdiff.py", line 6, in <module>
        import rpm
    ModuleNotFoundError: No module named 'rpm'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-dnho4wz2/
```

**Comment by EvaSDK** [comment]
I see this is shipped with the rpm source code now. A bit annoying but ok.
