### ISSUE TITLE
1.7 debian test failure

### ISSUE THREAD

**Issue by aborrero** [rpm-software-management/rpmlint#47]
Hi there!

I'm playing with the 1.7 release in Debian.

When building I found this issue:
```
[...]
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
Traceback (most recent call last):
  File "/tmp/buildd/rpmlint-1.7/test//test.SpecCheck.py", line 7, in <module>
    import SpecCheck
  File "/tmp/buildd/rpmlint-1.7/SpecCheck.py", line 22, in <module>
    from TagsCheck import VALID_GROUPS
  File "/tmp/buildd/rpmlint-1.7/TagsCheck.py", line 405, in <module>
    VALID_GROUPS = Pkg.get_default_valid_rpmgroups()
  File "/tmp/buildd/rpmlint-1.7/Pkg.py", line 200, in get_default_valid_rpmgroups
    with InstalledPkg("rpm") as p:
  File "/tmp/buildd/rpmlint-1.7/Pkg.py", line 883, in __init__
    raise KeyError(name)
KeyError: 'rpm'
Makefile:67: recipe for target 'check' failed
[...]
```

Is this a missing dependency on a python lib or something?

Thanks :-)

**Comment by scop** [comment]
No, a missing "rpm" package installed in the rpmdb. But that's a regression fixed by the above commit.

**Comment by aborrero** [comment]
It works, thanks.
