### ISSUE TITLE
Checking an installed package results in DuplicatesCheck dying with an exception

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [rpm-software-management/rpmlint#638]
```
abuild@conjecture:/home/abuild> rpmlint -i rpmlint
Traceback (most recent call last):
  File "/usr/bin/rpmlint", line 11, in <module>
    load_entry_point('rpmlint==2.0.0', 'console_scripts', 'rpmlint')()
  File "/usr/lib/python3.8/site-packages/rpmlint/cli.py", line 174, in lint
    sys.exit(lint.run())
  File "/usr/lib/python3.8/site-packages/rpmlint/lint.py", line 100, in run
    return self._run()
  File "/usr/lib/python3.8/site-packages/rpmlint/lint.py", line 69, in _run
    self.validate_installed_packages(self._load_installed_rpms(self.options['installed']))
  File "/usr/lib/python3.8/site-packages/rpmlint/lint.py", line 208, in validate_installed_packages
    self.run_checks(pkg)
  File "/usr/lib/python3.8/site-packages/rpmlint/lint.py", line 261, in run_checks
    fn(pkg)
  File "/usr/lib/python3.8/site-packages/rpmlint/checks/DuplicatesCheck.py", line 56, in check
    st = os.stat(pkg.dirName() + "/" + first)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/rpmlint.rpmlint.xauxnpps//usr/lib/python3.8/site-packages/rpmlint/__pycache__/__init__.cpython-38.pyc'
```

Digging into this, `pkg.dirName()` is the unpacked directory, which is fine and in use when checking provided RPM files, but that directory is empty when checking installed packages. The only workaround I can think of is forcing `dirName` to return '' for installed packages, but I am not familiar with rpm's python bindings at all.

**Comment by s-t-e-v-e-n-k** [comment]
Nice work! I think you've left a debug print in that linked commit.

**Comment by marxin** [comment]
> Nice work!
Thanks
> I think you've left a debug print in that linked commit.
You are right, I've just cleaned that up.
