### ISSUE TITLE
rpmlint run against installed packages does not work properly

### ISSUE THREAD

**Issue by spotrh** [rpm-software-management/rpmlint#671]
Originally reported [here](https://bugzilla.redhat.com/show_bug.cgi?id=1976254), when rpmlint -i is used on an installed package, the results are not correct.

The original reporter noticed that it appears to be trying to check files in /tmp rather than the installed files, but it seems like the type of check results in different errors.

For example, for R-core:

```
[spot@localhost ~]$ rpm -q R-core
R-core-4.1.0-1.fc35.x86_64
[spot@localhost ~]$ rpmlint -i R-core
Traceback (most recent call last):
  File "/usr/bin/rpmlint", line 33, in <module>
    sys.exit(load_entry_point('rpmlint==2.0.0', 'console_scripts', 'rpmlint')())
  File "/usr/lib/python3.9/site-packages/rpmlint/cli.py", line 174, in lint
    sys.exit(lint.run())
  File "/usr/lib/python3.9/site-packages/rpmlint/lint.py", line 100, in run
    return self._run()
  File "/usr/lib/python3.9/site-packages/rpmlint/lint.py", line 69, in _run
    self.validate_installed_packages(self._load_installed_rpms(self.options['installed']))
  File "/usr/lib/python3.9/site-packages/rpmlint/lint.py", line 205, in validate_installed_packages
    self.run_checks(pkg)
  File "/usr/lib/python3.9/site-packages/rpmlint/lint.py", line 258, in run_checks
    fn(pkg)
  File "/usr/lib/python3.9/site-packages/rpmlint/checks/AbstractCheck.py", line 17, in check
    return self.check_binary(pkg)
  File "/usr/lib/python3.9/site-packages/rpmlint/checks/AbstractCheck.py", line 49, in check_binary
    raise err
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/site-packages/rpmlint/checks/BashismsCheck.py", line 31, in check_file
    self.check_bashisms(pkg, filepath, filename)
  File "/usr/lib/python3.9/site-packages/rpmlint/checks/BashismsCheck.py", line 47, in check_bashisms
    raise FileNotFoundError(filename)
FileNotFoundError: /usr/bin/R
[spot@localhost ~]$ ls -l /usr/bin/R
-rwxr-xr-x. 1 root root 8954 Sep 25  2018 /usr/bin/R
[spot@localhost ~]$ 
```

And evolution:

```
[spot@localhost ~]$ rpm -q evolution
evolution-3.40.2-1.fc34.x86_64
[spot@localhost ~]$ rpmlint -i evolution
Traceback (most recent call last):
  File "/usr/bin/rpmlint", line 33, in <module>
    sys.exit(load_entry_point('rpmlint==2.0.0', 'console_scripts', 'rpmlint')())
  File "/usr/lib/python3.9/site-packages/rpmlint/cli.py", line 174, in lint
    sys.exit(lint.run())
  File "/usr/lib/python3.9/site-packages/rpmlint/lint.py", line 100, in run
    return self._run()
  File "/usr/lib/python3.9/site-packages/rpmlint/lint.py", line 69, in _run
    self.validate_installed_packages(self._load_installed_rpms(self.options['installed']))
  File "/usr/lib/python3.9/site-packages/rpmlint/lint.py", line 205, in validate_installed_packages
    self.run_checks(pkg)
  File "/usr/lib/python3.9/site-packages/rpmlint/lint.py", line 258, in run_checks
    fn(pkg)
  File "/usr/lib/python3.9/site-packages/rpmlint/checks/AbstractCheck.py", line 17, in check
    return self.check_binary(pkg)
  File "/usr/lib/python3.9/site-packages/rpmlint/checks/AbstractCheck.py", line 52, in check_binary
    self.check_file(pkg, filename)
  File "/usr/lib/python3.9/site-packages/rpmlint/checks/MenuXDGCheck.py", line 60, in check_file
    self.parse_desktop_file(pkg, root, f, filename)
  File "/usr/lib/python3.9/site-packages/rpmlint/checks/MenuXDGCheck.py", line 35, in parse_desktop_file
    with codecs.open(f, encoding='utf-8') as inputf:
  File "/usr/lib64/python3.9/codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/rpmlint.evolution.7727umhz/usr/share/applications/org.gnome.Evolution.desktop'
[spot@localhost ~]$ 
```

**Comment by marxin** [comment]
Confirmed, I can reproduce it locally. Working on that right now ...

**Comment by spotrh** [comment]
Thanks for the quick fix, confirmed on my end.

**Comment by marxin** [comment]
You're welcome, it was easy to fix.
