### ISSUE TITLE
CI (normal, registry.opensuse.org/opensuse/leap-dnf:15.3)

### ISSUE THREAD

**Issue by marxin** [rpm-software-management/rpmlint#707]
The CI fails with:

```
 dnf --assumeyes install checkbashisms dash desktop-file-utils appstream-glib myspell-en_US myspell-cs_CZ python3-pyenchant
  shell: sh -e {0}
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/libdnf/conf.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: librpm.so.8: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/dnf", line 57, in <module>
    from dnf.cli import main
  File "/usr/lib/python3.6/site-packages/dnf/__init__.py", line 30, in <module>
    import dnf.base
  File "/usr/lib/python3.6/site-packages/dnf/base.py", line 29, in <module>
    import libdnf.transaction
  File "/usr/lib64/python3.6/site-packages/libdnf/__init__.py", line 12, in <module>
    from . import conf
  File "/usr/lib64/python3.6/site-packages/libdnf/conf.py", line 17, in <module>
    _conf = swig_import_helper()
  File "/usr/lib64/python3.6/site-packages/libdnf/conf.py", line 16, in swig_import_helper
    return importlib.import_module('_conf')
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_conf
```

@Conan-Kudo Do you what has changed?

**Comment by Conan-Kudo** [comment]
What the heck? @lkocman, what happened here?!

**Comment by Vogtinator** [comment]
The cause is earlier in the CI run:

```
Errors during downloading metadata for repository 'opensuse-leap-sle-update':
  - Status code: 404 for http://ewr.edge.kernel.org/opensuse/update/leap/15.3/sle/repodata/5f92ba3085f2c4fbbd297a131be5cbf3f0ff6d90078b6380aba5c5002cfe6959-filelists.xml.gz (IP: 147.75.197.195)
  - Status code: 404 for http://ewr.edge.kernel.org/opensuse/update/leap/15.3/sle/repodata/6e2c8bc094a821a372ced6bd0c58cba9b69dcd42f90a0ce574300d440b0361b9-updateinfo.xml.gz (IP: 147.75.197.195)
  - Status code: 404 for http://ewr.edge.kernel.org/opensuse/update/leap/15.3/sle/repodata/08928d4f42da3d9f763163b1a61a072e8c13929c2eb194ffe7af08a46f5121db-primary.xml.gz (IP: 147.75.197.195)
Error: Failed to download metadata for repo 'opensuse-leap-sle-update': Yum repo downloading error: Downloading error(s): 
```

Without that repo, packages are missing and this breaks the system:

```
Downgrading:
 python3-rpm               x86_64 4.14.1-29.2           opensuse-leap-oss  56 k
 rpm                       x86_64 4.14.1-29.46          opensuse-leap-oss 1.5 M
```

Locally this results in a different error though: `ImportError: /usr/lib64/libdnf.so.2: undefined symbol: rpmtsSetVfyLevel`.

No idea why `librpm.so.8` is completely missing there, it's part of `rpm-4.14.1-29.46` as well.
