### ISSUE TITLE
TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/rpmlint#75]
```python
$ rpmlint /home/brain/rpmbuild/RPMS/noarch/python-geoip2-doc-2.4.0-1.fc25.noarch.rpm 
0 packages and 0 specfiles checked; 0 errors, 0 warnings.
Traceback (most recent call last):
  File "/usr/bin/rpmlint", line 385, in <module>
    main()
  File "/usr/bin/rpmlint", line 161, in main
    runChecks(pkg)
  File "/usr/bin/rpmlint", line 220, in runChecks
    check.check(pkg)
  File "/usr/share/rpmlint/AbstractCheck.py", line 52, in check
    return self.check_binary(pkg)
  File "/usr/share/rpmlint/DistributionCheck.py", line 40, in check_binary
    for fname in pkg.files():
  File "/usr/share/rpmlint/Pkg.py", line 601, in files
    self._gatherFilesInfo()
  File "/usr/share/rpmlint/Pkg.py", line 699, in _gatherFilesInfo
    elif Pkg._magic_from_compressed_re.search(pkgfile.magic):
TypeError: cannot use a string pattern on a bytes-like object
```

python3-magic-5.28-1.fc25.noarch

I guess this is since last update of magic/file.

**Comment by scop** [comment]
This is already fixed in master, 67543ee0365bb0da37231c1cfaf08a7f4ca0c8bb in particular. Will push a new release in a jiffy.
