### ISSUE TITLE
'SystemdTmpfilesCheck' object has no attribute 'm_arg'

### ISSUE THREAD

**Issue by marxin** [rpm-software-management/rpmlint#869]
The following package fails:
https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:B/systemd:mini/standard/x86_64

with:
```
[  194s] (none): E: fatal error while reading //home/abuild/rpmbuild/RPMS/x86_64/systemd-mini-250.5-3.8.x86_64.rpm: 'SystemdTmpfilesCheck' object has no attribute 'm_arg'
[  194s] Traceback (most recent call last):
[  194s]   File "/opt/testing/bin/rpmlint.real", line 33, in <module>
[  194s]     sys.exit(load_entry_point('rpmlint==2.3.0', 'console_scripts', 'rpmlint')())
[  194s]   File "./rpmlint/cli.py", line 185, in lint
[  194s]   File "./rpmlint/lint.py", line 108, in run
[  194s]   File "./rpmlint/lint.py", line 79, in _run
[  194s]   File "./rpmlint/lint.py", line 243, in validate_files
[  194s]   File "./rpmlint/lint.py", line 267, in validate_file
[  194s]   File "./rpmlint/lint.py", line 260, in validate_file
[  194s]   File "./rpmlint/lint.py", line 276, in run_checks
[  194s]   File "./rpmlint/checks/AbstractCheck.py", line 17, in check
[  194s]   File "./rpmlint/checks/SystemdTmpfilesCheck.py", line 262, in check_binary
[  194s]   File "./rpmlint/checks/SystemdTmpfilesCheck.py", line 262, in <lambda>
[  194s]   File "./rpmlint/checks/SystemdTmpfilesCheck.py", line 199, in _is_sensitive_entry
[  194s] AttributeError: 'SystemdTmpfilesCheck' object has no attribute 'm_arg'
```

**Comment by mgerstner** [comment]
Ah this is a minor regression left over from refactoring the code during development of the check. I will provide a fix soon.
